#!/bin/bash

verbose='false'
aflag=''
bflag=''
files=''


# Loop through arguments
while getopts 'mcr' flag; do

  case "${flag}" in

  	# Commit message
    m) 
		
		repo_string=$""	 # Added to auto-commits
		git_string="git commit" # Run as bitbucket push command
		
		# For loop requires -m "message" -m "message"  ... structure.
		for index in "$@"
		do
			if [ "$index" != "-m" ]; then
				git_string+=" -m \"$index\""
				repo_string+="
$index"
			fi
		done
		
		# push to bitbucket
		eval $git_string
		git push
		echo "bitbucket push successful"

		# auto-commit to github
		sudo printf "$repo_string">/etc/bitbucket-commits/commits
		cd /etc/bitbucket-commits
		git add commits
		git commit -m "Auto-Commit"
		git push
		echo "github push successful"
		;;

	# Configure Repo and Config file
	c) 
		echo "github_url=\"$2\"">/etc/.bitbucket.cfg
		# mkdir /etc/bitbucket-commits
		# cd /etc/bitbucket-commits
		echo "$2 - File of commits to new private bitbucket repository added">/etc/bitbucket-commits/commits
		# git init
		git remote add origin "$2"
		# git push origin master
		echo "config established at /etc/.bitbucket.cfg"
		echo "auto directory established at /etc/bitbucket-commits"
		;;
	*) error "Unexpected option ${flag}" ;;
  esac
done

