#!/bin/bash

verbose='false'
aflag=''
bflag=''
files=''


# String 'mc' is list of flags.
while getopts 'mcr' flag; do

	# Flag -m -c
  case "${flag}" in
    m) 
		repo_string=$""
		git_string=""
		for index in "$@"
		do
			if [ "$index" != "-m" ]; then
				git_string+=" -m \"$index\""
				repo_string+="
$index"
			fi
		done
		
		printf "$repo_string">/etc/bitbucket-commits/commits
		echo "$git_string"
		cd /etc/bitbucket-commits
		git add commits
		git commit $git_string
		git push
		cd .
		ls
		;;
	c) 
		echo "github_url=\"$2\"">/etc/.bitbucket.cfg
		mkdir /etc/bitbucket-commits
		cd /etc/bitbucket-commits
		echo "$2 - File of commits to new private bitbucket repository added">/etc/bitbucket-commits/commits
		git init
		git remote add origin "$2"
		git push origin master
		;;
	r) source .bitbucket.cfg
		echo "$github_url"
		;;
    *) error "Unexpected option ${flag}" ;;
  esac
done


# bitbucket-commit -c "git@github.com@amsully/bitbucket-commits.com"
	# set git_repo variable to  -> 
	# create file txt for messages
# bitbucket-commit -m "TITLE" -m "Description"
	# git commit -m "TITLE" -m "Description" -- this commits to butbucket
	# open local file 
	# cat the messages -
	# push to git repo



